export const encodedLabels = {
  genus_species: [
    'Afarensis',
    'Africanus',
    'Anamensis',
    'Bahrelghazali',
    'Garhi',
    'Sediba',
    'Antecesor',
    'Erectus',
    'Ergaster',
    'Floresiensis',
    'Georgicus',
    'Habilis',
    'Heidelbergensis',
    'Naledi',
    'Neanderthalensis',
    'Rodhesiensis',
    'Rudolfensis',
    'Sapiens',
    'Aethiopicus',
    'Boisei',
    'Robustus',
    'Ramidusç',
    'Tugenencin',
    'Tchadensis',
  ],
  location: ['Africa', 'Asia', 'Europa'],
  zone: ['central', 'oriental', 'south', 'west'],
  current_country: [
    'Etiopia',
    'Georgia',
    'Alemania',
    'Indonesia',
    'Kenia',
    'Republica de Chad',
    'Sudafrica',
    'Espana',
  ],
  habitat: [
    'cold forest',
    'forest',
    'forest-gallery',
    'forest-savanna',
    'jungle',
    'mixed',
    'peninsular',
    'savannah',
  ],
  incisor_size: ['big', 'medium large', 'megadony', 'small', 'very small'],
  jaw_shape: ['U shape', 'V shape', 'conical', 'modern'],
  torus_supraorbital: [
    'flat',
    'less protruding',
    'little protruding',
    'ultra protruding',
    'very protruding',
  ],
  prognathism: [
    'absent',
    'high',
    'medium',
    'medium-high',
    'reduced',
    'very high',
  ],
  foramen_magnum_position: ['anterior', 'modern', 'posterior', 'semi-anterior'],
  canine_size: ['big', 'small'],
  canines_shape: ['conicalls', 'incisiform'],
  tooth_enamel: [
    'medium-thick',
    'medium-thin',
    'thick',
    'thick-medium',
    'thin',
    'very thick',
    'very thin',
  ],
  tecno_culture: ['likely', 'no', 'yes'],
  tecno_type: ['mode 1', 'mode 2', 'mode 3', 'mode 4', 'no', 'primitive'],
  bipedalism: ['high probability', 'low probability', 'modern', 'yes'],
  arms_length: ['climbing', 'manipulate', 'manipulate with precision'],
  feet_structure: ['climbing', 'walk'],
  diet_type: [
    'carnivora',
    'frutos secos',
    'frutas duras',
    'omnivora',
    'frutas blandas',
  ],
  sexual_dimorphism: ['high', 'medium-high', 'reduced'],
  hip_structure: ['modern', 'slim', 'very modern', 'wide'],
  vertical_front_structure: ['modern', 'no', 'yes'],
  anatomy_features: ['mixed', 'modern', 'old', 'very modern'],
  migrated: ['no', 'yes'],
  skeleton_features: ['light', 'refined', 'robust'],
}
